#!/usr/bin/env python3
"""
Assemble a standalone harness out of the fake Roblox environment, so any Luau
script can be run against it outside the deobfuscator:

    python3 build_env.py <script.lua> [-o harness.luau] [--cfg k=v ...]

The result is a single self-contained file: the script source, the config, the
API dump, the datatype models, the unicode tables and the runtime, then the
runtime runs the script and prints the trace between the \\0ENVLOG-BEGIN and
\\0ENVLOG-END sentinels. Run it with the bundled `luau`:

    ./luau harness.luau | ./extract_trace.py     # readable trace on stdout
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PARTS = ("envlog.luau", "unicode_data.luau", "roblox_api.luau", "datatypes.luau")


def read(name, ascii_only=False):
    with open(os.path.join(HERE, name), encoding="ascii" if ascii_only else "utf-8") as f:
        return f.read()


def long_string(s):
    """A [==[ ... ]==] literal that survives any content (harness.py does the same)."""
    level = 0
    while ("]" + "=" * level + "]") in s:
        level += 1
    eq = "=" * level
    return "[" + eq + "[\n" + s + "]" + eq + "]"


def lua_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        if "\n" in v:
            return long_string(v)
        return '"%s"' % v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    if isinstance(v, (list, tuple)):
        return "{" + ", ".join(lua_value(x) for x in v) + "}"
    if isinstance(v, dict):
        return "{" + ", ".join("[%s] = %s" % (lua_value(k), lua_value(val))
                               for k, val in v.items()) + "}"
    return "nil"


def build(source, cfg, out_path):
    missing = [p for p in PARTS if not os.path.exists(os.path.join(HERE, p))]
    if missing:
        sys.exit("missing environment parts: " + ", ".join(missing))
    runtime = read("envlog.luau").replace("--!nocheck", "", 1)
    text = (
        "-- Generated by build_env.py: a protected script running against the fake\n"
        "-- Roblox/executor environment. Do not edit; rebuild instead.\n"
        "--!nocheck\n"
        "local __SOURCE = " + long_string(source) + "\n"
        "local __CONFIG = {" + ", ".join("%s = %s" % (k, lua_value(v)) for k, v in cfg.items()) + "}\n"
        "local __P2D = {}\n"
        "local __CHUNKS = {}\n"
        "local __UNICODE = (function()\n" + read("unicode_data.luau", True) + "\nend)()\n"
        "local __ROBLOX = (function()\n" + read("roblox_api.luau", True) + "\nend)()\n"
        "__ROBLOX.datatypes = (function()\n"
        + read("datatypes.luau").replace("--!nocheck", "", 1) + "\nend)()\n" + runtime)
    with open(out_path, "w", encoding="latin-1", newline="\n") as f:
        f.write(text)
    return out_path


def main():
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("script", help="the Luau script to run inside the environment")
    ap.add_argument("-o", "--out", default="", help="harness file (default harness.luau)")
    ap.add_argument("--cfg", action="append", default=[], metavar="KEY=VALUE",
                    help="runtime option, e.g. trace=false, max_stmts=50000, "
                         "prelude=rawset(G,'key','x'), falsy=isexploitclosure")
    args = ap.parse_args()
    with open(args.script, encoding="latin-1") as f:
        source = f.read()
    cfg = {}
    for item in args.cfg:
        k, _, v = item.partition("=")
        if v in ("true", "false"):
            cfg[k] = v == "true"
        elif v.isdigit():
            cfg[k] = int(v)
        else:
            cfg[k] = v
    out = args.out or os.path.join(os.getcwd(), "harness.luau")
    build(source, cfg, out)
    print("[+] wrote %s (%.1f MB, %d cfg entries)"
          % (out, os.path.getsize(out) / 1e6, len(cfg)))


if __name__ == "__main__":
    main()
