from __future__ import annotations

import argparse
import json
import shutil
import sys
import urllib.request
from pathlib import Path

from .environment import RobloxEnvironment
from .native import validate_luau
from .pipeline import Pipeline, process_file

RAW_GAMES_URL = "https://raw.githubusercontent.com/joustingmatch/Ouroboros/main/games/{name}"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="luau-recover", description="Recover readable Luau from LuaST-style obfuscation")
    parser.add_argument("inputs", nargs="*", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--max-iterations", type=int, default=15)
    parser.add_argument("--error-log", type=Path)
    parser.add_argument("--report", action="store_true")
    parser.add_argument("--no-aggressive", action="store_true")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    parser.add_argument("--env-run", action="store_true")
    parser.add_argument("--env-only", action="store_true")
    parser.add_argument("--env-dir", type=Path)
    parser.add_argument("--env-trace-dir", type=Path)
    parser.add_argument("--env-timeout", type=int, default=120)
    parser.add_argument("--env-config", action="append", default=[])
    parser.add_argument("--env-prelude")
    parser.add_argument("--env-falsy", action="append", default=[])
    parser.add_argument("--native-validate", action="store_true")
    parser.add_argument("--native-timeout", type=int, default=120)
    parser.add_argument("--fetch", action="append", default=[],
                        help="fetch a game script live from the Ouroboros raw "
                             "GitHub repo (games/<name>) and deobfuscate it")
    parser.add_argument("--fetch-dir", type=Path,
                        help="where to store fetched scripts (default: <project>/FETCHED)")
    parser.add_argument("--no-l3", action="store_true",
                        help="skip the dedicated LUAST-L3 emulator even if the "
                             "input looks like level-3 output")
    return parser


def looks_like_luast_l3(path: Path) -> bool:
    try:
        head = path.open("rb").read(262144).decode("utf-8", "surrogateescape")
    except Exception:
        return False
    if "-- generated by luast" not in head:
        return False
    # level 3 threads a Z accumulator through the dispatcher
    for token in ("while true do", "continue", "bit32.bxor", "buffer.readu32"):
        if token not in head:
            return False
    return True


def run_l3(source: Path, target: Path, report_path: Path | None) -> bool:
    """Run the dedicated L3 emulator; True when it produced output."""
    from . import luast_l3

    argv = [str(source), "-o", str(target)]
    if report_path is not None:
        argv += ["--report", str(report_path)]
    import io
    from contextlib import redirect_stdout
    buf = io.StringIO()
    try:
        with redirect_stdout(buf):
            code = luast_l3.main(argv)
    except SystemExit as exc:  # argparse paths
        code = exc.code
    except Exception as exc:
        print(f"l3: {source.name}: {type(exc).__name__}: {exc}", file=sys.stderr)
        return False
    if code not in (0, None):
        sys.stderr.write(buf.getvalue())
        return False
    sys.stdout.write(buf.getvalue())
    return target.exists() and target.stat().st_size > 0


def input_files(paths: list[Path]) -> list[Path]:
    result: list[Path] = []
    for path in paths:
        if path.is_dir():
            result.extend(sorted(item for item in path.iterdir() if item.is_file()))
        else:
            result.append(path)
    return result


def destination(source: Path, args: argparse.Namespace, index: int) -> Path:
    if args.output and len(args.inputs) + len(args.fetch) == 1:
        return args.output
    if args.output_dir:
        return args.output_dir / source.name
    if args.output and len(args.inputs) == 1:
        return args.output
    project_root = Path(__file__).resolve().parents[2]
    return project_root / "DEOBFUSCATED" / source.name


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    inputs = list(args.inputs)
    fetch_failures = 0
    if args.fetch:
        fetch_dir = args.fetch_dir or Path(__file__).resolve().parents[2] / "FETCHED"
        fetch_dir.mkdir(parents=True, exist_ok=True)
        for name in args.fetch:
            url = RAW_GAMES_URL.format(name=name)
            dest = fetch_dir / Path(name).name
            try:
                with urllib.request.urlopen(url, timeout=60) as resp:
                    data = resp.read()
            except Exception as exc:
                print(f"fetch failed: {url}: {exc}", file=sys.stderr)
                fetch_failures += 1
                continue
            dest.write_bytes(data)
            print(f"fetched {url} -> {dest} ({len(data)} bytes)")
            inputs.append(dest)

    files = input_files(inputs)
    if not files:
        print("no input files", file=sys.stderr)
        return 2 if not fetch_failures else 1
    failures = fetch_failures
    reports = []
    for index, source in enumerate(files):
        if not source.is_file():
            print(f"missing input: {source}", file=sys.stderr)
            failures += 1
            continue
        target = destination(source, args, index)
        entry: dict[str, object] = {"input": str(source), "output": str(target)}
        try:
            if not args.env_only and not args.no_l3 and looks_like_luast_l3(source):
                report_path = target.with_suffix(".l3report.txt")
                if run_l3(source, target, report_path):
                    entry["status"] = "ok-l3"
                    entry["valid_output"] = True
                    if not args.quiet:
                        print(f"ok-l3 {source.name} -> {target}")
                    reports.append(entry)
                    continue
                print(f"l3 emulator did not resolve {source.name}; "
                      "falling back to the generic pipeline", file=sys.stderr)
            if not args.env_only:
                report = process_file(source, target, max_iterations=args.max_iterations, aggressive=not args.no_aggressive, error_log=args.error_log)
                entry.update(report.as_dict())
                if not args.quiet:
                    status = "ok" if report.valid_output else "fallback"
                    print(f"{status} {source.name} -> {target} ({report.output_bytes} bytes, {report.elapsed_seconds:.2f}s)")
                if not report.valid_output:
                    failures += 1
            if args.native_validate and target.exists():
                native = validate_luau(target, args.env_dir or Path(__file__).resolve().parents[2] / "ROBLOX_ENV", args.native_timeout)
                entry["native_validation"] = native
                if native.get("available") and not native.get("valid"):
                    shutil.copyfile(source, target)
                    entry["status"] = "native-invalid"
                    entry["valid_output"] = False
                    failures += 1
            if args.env_run or args.env_only:
                project_env = Path(__file__).resolve().parents[2] / "ROBLOX_ENV"
                environment = RobloxEnvironment(args.env_dir or project_env, timeout=args.env_timeout)
                project_root = Path(__file__).resolve().parents[2]
                trace_dir = args.env_trace_dir or project_root / "DEOBFUSCATED" / "ENV_TRACES"
                trace_path = trace_dir / (target.stem + ".trace.luau")
                env_report = environment.run(source, trace_path, config=args.env_config, prelude=args.env_prelude, falsy=args.env_falsy)
                entry["environment"] = env_report.as_dict()
                if not args.quiet:
                    print(f"env {env_report.status} {source.name} -> {trace_path} ({env_report.trace_bytes} bytes)")
        except Exception as exc:
            failures += 1
            print(f"{source}: {type(exc).__name__}: {exc}", file=sys.stderr)
            continue
        reports.append(entry)
    if args.report:
        json.dump(reports, sys.stdout, indent=2, ensure_ascii=False)
        sys.stdout.write("\n")
    if args.strict and failures:
        return 1
    return 0
