#!/usr/bin/env python3
"""LUAST obfuscation detector.

Identifies LUAST-obfuscated Lua(u) scripts, fingerprints the obfuscator
version, presets/level and output style, and reports confidence.

Usage:
    python3 detector.py <file-or-dir>... [-v]
    python3 detector.py --demo          # run on bundled test vectors
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path


# ---------------------------------------------------------------- fingerprints

LUAST_HEADER_RE = re.compile(
    r"--\s*generated by luast\s*v?([0-9]+(?:\.[0-9]+)*)\s*(https?://\S+)?")

# constant pool bigrams of the xxHash64-style round function used by
# LUAST v1.0.x level 2/3 payload decoders (2654435769 = fractional part of
# the golden ratio, 2246822507/3266489909/668265263/374761393/4283543511
# = xxHash64 PRIME64 constants; 16807/2147483647 = the classic minstd LCG)
ROUND_CONSTANTS = (
    "2654435769", "2246822507", "3266489909", "668265263",
    "374761393", "4283543511", "16807", "2147483647", "2147483646",
    "4294967296",
)

# every level ships a self-identifying header; older 0.x builds did not
NO_HEADER_MARKERS = ("while true do", "continue")

# library aliases created at the top of every file
ALIAS_RE = re.compile(
    r"local\s+[A-Za-z_][A-Za-z0-9_]*\s*=\s*"
    r"(bit32\.(?:bxor|band|bor|rshift|lshift|lrotate|rrotate)"
    r"|string\.(?:byte|char|rep|sub|format|len)"
    r"|buffer\.(?:fromstring|tostring|readu32|readu8|readstring|writeu32|writeu8|readi16|len|offset)"
    r"|math\.(?:sign|floor|abs|max|min|sqrt|clamp)"
    r"|table\.(?:isfrozen|insert|remove|concat|find)"
    r"|debug\.info"
    r"|coroutine\.(?:resume|create|yield|close))")

ROBLOX_TYPE_RE = re.compile(
    r"\b(Instance|CFrame|Vector3|Vector2|Vector2int16|Vector3int16|Color3|"
    r"ColorSequence|NumberSequence|NumberRange|BrickColor|UDim|UDim2|Rect|"
    r"Region3|Ray|TweenInfo|Random|DateTime|Font|Enum|task|vector)\b")

# decoy string shape: 3-12 lowercase letters, no vowels-patterning check is
# intentionally loose; scoring uses entropy + dictionary misses instead
DECOY_STR_RE = re.compile(r'"([a-z]{3,12})"')

COMMON_WORDS = {
    "the", "and", "for", "not", "are", "you", "all", "new", "was", "can",
    "has", "but", "our", "one", "two", "may", "out", "get", "set", "put",
    "end", "row", "col", "key", "val", "url", "id", "ok", "err", "msg",
    "len", "sub", "rep", "byte", "char", "find", "format", "upper",
    "lower", "reverse", "insert", "remove", "concat", "floor", "sign",
    "abs", "max", "min", "sqrt", "clamp", "info", "name", "value", "type",
    "print", "pairs", "ipairs", "pcall", "error", "assert", "tostring",
    "select", "next", "game", "font", "true", "false", "weight", "style",
    "bold", "italic", "medium", "semibold", "heavy", "thin", "light",
    "plastic", "neon", "wood", "grass", "brick", "metal", "ice", "glass",
    "oneway", "swing", "linear", "inout", "outin", "in", "out", "quad",
    "cubic", "quart", "quint", "sine", "expo", "circ", "elastic", "back",
    "bounce",
}

PRESET_HINTS = {
    "level1": dict(min_pool=20, needs_vm_crypto=False, needs_buffer=False),
    "level2": dict(min_pool=20, needs_vm_crypto=True, needs_buffer=True),
    "level3": dict(min_pool=20, needs_vm_crypto=True, needs_buffer=True),
}


# ---------------------------------------------------------------- helpers

def shannon(s: str) -> float:
    if not s:
        return 0.0
    freq = {}
    for ch in s:
        freq[ch] = freq.get(ch, 0) + 1
    n = len(s)
    return -sum((c / n) * math.log2(c / n) for c in freq.values())


def looks_decoy(word: str) -> bool:
    """Heuristic for machine-generated identifier-like decoy strings."""
    if word.lower() in COMMON_WORDS:
        return False
    vowels = sum(1 for ch in word if ch in "aeiou")
    ratio = vowels / max(len(word), 1)
    if not 0.1 <= ratio <= 0.6:
        return True
    # alternating consonant/vowel patterns typical of random syllables
    return shannon(word) > 3.2 and len(word) >= 5


def hex_escape_strings(src: str) -> int:
    return len(re.findall(r'\\x[0-9a-fA-F]{2}', src))


def float_literals(src: str) -> int:
    """LUAST emits float literals with explicit '.0' as e.g. '24.' / '3.7'."""
    return len(re.findall(r'\b\d+\.\d*\b', src))


# ---------------------------------------------------------------- detection

@dataclass
class DetectResult:
    path: str = ""
    is_luast: bool = False
    confidence: float = 0.0
    version: str | None = None
    site: str | None = None
    preset: str | None = None
    output_style: str | None = None
    has_vm_crypto: bool = False
    has_buffer_decoder: bool = False
    pool_slots: int = 0
    dispatcher_states: int = 0
    decoy_ratio: float = 0.0
    entropy: float = 0.0
    sha256: str = ""
    notes: list[str] = field(default_factory=list)


def detect_luast(src: str, name: str = "<memory>") -> DetectResult:
    r = DetectResult(path=name)
    r.sha256 = hashlib.sha256(src.encode("utf-8", "surrogateescape")).hexdigest()

    header = LUAST_HEADER_RE.search(src[:4096])
    if header:
        r.is_luast = True
        r.version = header.group(1)
        r.site = header.group(2)
        r.confidence = max(r.confidence, 0.95)
        r.notes.append("self-identifying header: luast v%s" % r.version)
    else:
        # headerless builds: fall back to structural fingerprints
        score = 0.0
        if "while true do" in src and "continue" in src:
            score += 0.25
            r.notes.append("flattened dispatcher loop present")
        crypto_hits = sum(1 for c in ROUND_CONSTANTS if c in src)
        if crypto_hits >= 4:
            score += 0.45
            r.notes.append("xxHash64/minstd decoder constants x%d" % crypto_hits)
        if score >= 0.6:
            r.is_luast = True
            r.confidence = min(0.85, score + 0.15)
            r.version = None
            r.notes.append("version unknown (no header)")

    if not r.is_luast:
        return r

    # ---- structural fingerprints
    r.has_vm_crypto = all(c in src for c in ("2654435769", "4283543511"))
    r.has_buffer_decoder = "buffer.readu32" in src and "buffer.fromstring" in src

    aliases = len(set(ALIAS_RE.findall(src)))
    r.notes.append("library aliases: %d" % aliases)

    # pool size: biggest top-level table constructor heuristic — count the
    # multi-assign permutation slots; LUAST permutes the pool in long
    # `a,b,c = c,b,a` chains
    perm_slots = 0
    for m in re.finditer(r"([A-Za-z_]\w*)\[(\d+\.?\d*)\]", src):
        pass
    perm_chains = re.findall(r"(?:\w+\[\d+\.?\d*\]\s*,\s*){4,}\w+\[\d+\.?\d*\]\s*=", src)
    for chain in perm_chains:
        perm_slots = max(perm_slots, chain.count("["))
    r.pool_slots = perm_slots

    # dispatcher state count: distinct integer targets in `<st> = <n>` form
    states = set()
    m = re.search(r"while true do ([A-Za-z_]\w*) = ([0-9.]+) - \1", src)
    if m:
        st = m.group(1)
        for v in re.findall(re.escape(st) + r" = ([0-9]+)(?:\.0)?\b", src):
            states.add(int(v))
        for v in re.findall(re.escape(st) + r" = if .* then ([0-9]+)(?:\.0)? else", src):
            states.add(int(v))
    r.dispatcher_states = len(states)

    # decoy ratio: fraction of lowercase letter-only strings that look random
    words = DECOY_STR_RE.findall(src)
    if words:
        decoys = sum(1 for w in words if looks_decoy(w))
        r.decoy_ratio = decoys / len(words)

    r.entropy = shannon(src[:65536])

    # ---- preset / style inference
    if r.version and r.version.startswith("1."):
        if not r.has_vm_crypto and not r.has_buffer_decoder:
            r.preset = "level1"
        elif r.has_vm_crypto and r.has_buffer_decoder:
            # level2 vs level3: level3 injects a much denser decoy-string
            # surface into the pool (measured 0.19-0.39 vs 0.05-0.14 across
            # styles for v1.0.1).  Combined with the datatype-weighting
            # surface this gives a reliable split.
            r.notes.append("crypto: %s; buffer: %s; roblox types: %d"
                           % (r.has_vm_crypto, r.has_buffer_decoder,
                              len(set(ROBLOX_TYPE_RE.findall(src)))))
            if r.decoy_ratio >= 0.17:
                r.preset = "level3"
                r.notes.append("dense decoy pool -> level3")
            else:
                r.preset = "level2"
                r.notes.append("sparse decoy pool -> level2")

    # output style
    if "\n" not in src.rstrip("\n"):
        r.output_style = "single line"
    else:
        lines = src.splitlines()
        body = [ln for ln in lines if ln.strip()]
        if body and max(len(ln) for ln in body) > 2000:
            r.output_style = "compact"
        else:
            indented = sum(1 for ln in body if ln.startswith(("\t", "    ")))
            r.output_style = "pretty" if indented > len(body) * 0.3 else "compact"

    # confidence adjustments
    if r.has_vm_crypto:
        r.confidence = max(r.confidence, 0.9)
    if aliases >= 4:
        r.confidence = max(r.confidence, 0.75)
    if r.decoy_ratio > 0.3:
        r.confidence = max(r.confidence, 0.7)
        r.notes.append("decoy string ratio %.2f" % r.decoy_ratio)

    return r


# ---------------------------------------------------------------- demo vectors

DEMO_LEVEL3 = '''-- generated by luast v1.0.1 https://luast.clv.cloud
local aG = bit32.bxor; local aH = string.byte; local aI = bit32.band; local aK = bit32.rshift; local aL = buffer.readu32; local aM = string.char; local aN = buffer.readstring; local aO = buffer.readu8;
local aD; aD = { 378713, 11, "Bold", game.GetService, pcall, 16777213, Enum, 2246822507, 16807, "rep", 4294967296, "JSONDecode", 2654435769. };
local ae = nil; ae = 67; while true do ae = 13638. - ae; do if ae < 13597 then if ae == 13565 then Z += aD[191]; ae = 0. else ae = 13623.; continue end end end end
'''


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="LUAST obfuscation detector")
    ap.add_argument("paths", nargs="*", help="files or directories to scan")
    ap.add_argument("-v", "--verbose", action="store_true")
    ap.add_argument("--demo", action="store_true", help="run on built-in vectors")
    ap.add_argument("--json", action="store_true", help="JSON output")
    args = ap.parse_args(argv)

    targets: list[Path] = []
    for p in args.paths:
        path = Path(p)
        if path.is_dir():
            targets.extend(sorted(path.rglob("*.lua")))
            targets.extend(sorted(path.rglob("*.luau")))
        elif path.is_file():
            targets.append(path)

    results: list[DetectResult] = []
    if args.demo and not targets:
        results.append(detect_luast(DEMO_LEVEL3, "<demo-level3>"))
    for t in targets:
        try:
            src = t.read_text(encoding="utf-8", errors="replace")
        except Exception as exc:
            print(f"skip {t}: {exc}", file=sys.stderr)
            continue
        results.append(detect_luast(src, str(t)))

    if args.json:
        print(json.dumps([asdict(r) for r in results], indent=2))
    else:
        for r in results:
            flag = "LUAST" if r.is_luast else "clean"
            print(f"[{flag}] {r.path}  conf={r.confidence:.2f}")
            if r.is_luast:
                print(f"    version={r.version} preset={r.preset} style={r.output_style}")
                print(f"    crypto={r.has_vm_crypto} buffer={r.has_buffer_decoder} "
                      f"states={r.dispatcher_states} decoys={r.decoy_ratio:.2f}")
            if args.verbose:
                for n in r.notes:
                    print(f"    - {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
